myName = input("What's you name?: ")
myAge = input("How old are you? :")
print("Gee, that's REALLY OLD")
replit = input("Do you like Replit?")
print("OF COURSE YOU DO!")
print()
print("So, you are")
print(myName)
print("and are the ripe old age of")
print(myAge)
print("and clearly think that Replit is")
print(replit)
myGrandma = input("How's your Grandma doing? 😘 ")
print(myGrandma)
myLunch = input("What are you having for lunch? ")
print("Hmm, it sounds like you really should just order")
print(f"myLunch will be {myLunch}")
print("as soon as possible!")
print("Definitely not a Phishing Scam")
print()
myName = input("Your Name")
print("Thanks for logging in")
print(myName)
cardNumber = input("What is your credit card number?")
print("Thanks, I definitely wont put")
print(cardNumber)
print("into Amazon and order anything weird")
print()
print("Promise")
maidenName = input("What is your Mother's maiden name? ")
print()
print("That's cool, I just wanted to know that")
print(maidenName)
print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")
print("Getting to know you!")

YourName = input("What is your name?")
Hungry = input ("What is your favorite food?")
Music = input("What is your favorite music?")
WhereAreYou = input("Where are you?")

print("You are")
print(YourName)
print() 

print("You're probably hungry for")
print(Hungry)
print()
print("You're probably listening to")
print (Music)
print()
print ("You're probably living in the amazing")
print (WhereAreYou)
print() 
print ("Have a great day!")